In [137]:
#1. Import the NUMPY package under the name np.
import numpy as np
#2. Print the NUMPY version and the configuration.
print(np.__version__)



1.16.2


In [138]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.random((2,3,5))


#4. Print a.

print(a)



[[[0.47599863 0.05653441 0.11805379 0.63563676 0.63160347]
  [0.31899473 0.94365689 0.28040012 0.72667676 0.45265079]
  [0.61693605 0.18107868 0.32845838 0.59449591 0.78989338]]

 [[0.78887922 0.580322   0.83061779 0.72052538 0.15894182]
  [0.08007403 0.79409395 0.58461222 0.48293898 0.40116454]
  [0.23124419 0.63502246 0.02232195 0.5129496  0.13619579]]]


In [139]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.random.random((5,2,3))
b.fill(1)



#6. Print b.
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [140]:


#7. Do a and b have the same size? How do you prove that in Python code?
b.size == a.size



True

In [141]:
print(a.shape)
print(b.shape)

(2, 3, 5)
(5, 2, 3)


In [142]:


#8. Are you able to add a and b? Why or why not?
# We cannot add a and b because they don't have the same shape


#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = np.transpose(b, (1,2,0))

print(c)
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
print(c.shape)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(2, 3, 5)


In [143]:

d = np.add(a, c)

#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print(d)



#12. Multiply a and c. Assign the result to e.
e = np.multiply(a, c)

print(e)
#13. Does e equal to a? Why or why not?




#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)


[[[0.47599863 0.05653441 0.11805379 0.63563676 0.63160347]
  [0.31899473 0.94365689 0.28040012 0.72667676 0.45265079]
  [0.61693605 0.18107868 0.32845838 0.59449591 0.78989338]]

 [[0.78887922 0.580322   0.83061779 0.72052538 0.15894182]
  [0.08007403 0.79409395 0.58461222 0.48293898 0.40116454]
  [0.23124419 0.63502246 0.02232195 0.5129496  0.13619579]]]
[[[1.47599863 1.05653441 1.11805379 1.63563676 1.63160347]
  [1.31899473 1.94365689 1.28040012 1.72667676 1.45265079]
  [1.61693605 1.18107868 1.32845838 1.59449591 1.78989338]]

 [[1.78887922 1.580322   1.83061779 1.72052538 1.15894182]
  [1.08007403 1.79409395 1.58461222 1.48293898 1.40116454]
  [1.23124419 1.63502246 1.02232195 1.5129496  1.13619579]]]
[[[0.47599863 0.05653441 0.11805379 0.63563676 0.63160347]
  [0.31899473 0.94365689 0.28040012 0.72667676 0.45265079]
  [0.61693605 0.18107868 0.32845838 0.59449591 0.78989338]]

 [[0.78887922 0.580322   0.83061779 0.72052538 0.15894182]
  [0.08007403 0.79409395 0.58461222 0.48293898

In [158]:


#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty((2,3,5))

f.fill(0)



print(f)

print(d_max)
print(d_min)
print(d_mean)


[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
1.943656890565622
1.0223219490779996
1.4703657551423186


In [115]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""
#d = (f < d_min).astype(int)

for counter, element in enumerate(d):
        for counter2, subelement in enumerate(element):
            for counter3, subsubelement in enumerate(subelement):
                if subsubelement > d_min and subsubelement < d_mean:
                    f[counter][counter2][counter3] = 25
                elif subsubelement < d_max and subsubelement > d_mean:
                    f[counter][counter2][counter3] = 75
                elif subsubelement == d_mean:
                    f[counter][counter2][counter3] = 50
                elif subsubelement == d_max:
                    f[counter][counter2][counter3] = 100
                elif subsubelement == d_min:
                    f[counter][counter2][counter3] = 0
                    
                    
                    
                    
                    

print(d)
print(d_max)
print(d_min)
print(d_mean)
print(f)




[[[1.30580582 1.93952518 1.22288415 1.05914428 1.24370538]
  [1.20885413 1.4777137  1.33351943 1.95010328 1.37859669]
  [1.57519114 1.53003965 1.12964416 1.82062505 1.52971388]]

 [[1.75115608 1.89909403 1.03686588 1.56165668 1.3886439 ]
  [1.35155212 1.4628572  1.27921104 1.52379678 1.21988318]
  [1.00672169 1.29145804 1.52107148 1.66435158 1.86159621]]]
1.950103283690435
1.0067216868975941
1.4508327271709665
[[[ 25.  75.  25.  25.  25.]
  [ 25.  75.  25. 100.  25.]
  [ 75.  75.  25.  75.  75.]]

 [[ 75.  75.  25.  75.  25.]
  [ 25.  75.  25.  75.  25.]
  [  0.  25.  75.  75.  75.]]]


In [149]:
#f = np.where(d < d_mean and d > d_min, 25, d)
#np.where(f < d_mean, 25, d)

f = np.empty((2,3,5))

f.fill(0)

f = np.where((d < d_mean) & (d > d_min), 25, d)


f = np.where((f < d_max) & (f > d_mean), 75, f)
f = np.where(f == d_max, 100, f)
f = np.where(f == d_min, 0, f)
f = np.where(f == d_mean, 50, f)



print(f)

[[[ 75.  25.  25.  75.  75.]
  [ 25. 100.  25.  75.  25.]
  [ 75.  25.  25.  75.  75.]]

 [[ 75.  75.  75.  75.  25.]
  [ 25.  75.  75.  75.  25.]
  [ 25.  75.   0.  75.  25.]]]


In [159]:
f = np.empty((2,3,5))

f.fill(0)

f = np.where((d < d_mean) & (d > d_min), 25, np.where((d < d_max) & (d > d_mean), 75, np.where(d == d_max, 100, np.where(d == d_min, 0, np.where(d == d_mean, 50, d)))))


print(f)

[[[ 75.  25.  25.  75.  75.]
  [ 25. 100.  25.  75.  25.]
  [ 75.  25.  25.  75.  75.]]

 [[ 75.  75.  75.  75.  25.]
  [ 25.  75.  75.  75.  25.]
  [ 25.  75.   0.  75.  25.]]]


In [ ]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

In [161]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""
g = np.empty((2,3,5))

g.fill(0)


g = np.where((d < d_mean) & (d > d_min), "B", np.where((d < d_max) & (d > d_mean), "D", np.where(d == d_max, "E", np.where(d == d_min, "A", np.where(d == d_mean, "C", d)))))


print(g)


[[['D' 'B' 'B' 'D' 'D']
  ['B' 'E' 'B' 'D' 'B']
  ['D' 'B' 'B' 'D' 'D']]

 [['D' 'D' 'D' 'D' 'B']
  ['B' 'D' 'D' 'D' 'B']
  ['B' 'D' 'A' 'D' 'B']]]
